version: '3.8'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_ES_JAVA_OPTS=-Xms512m -Xmx512m
      - SONARQUBE_JAVA_OPTS=-Xms512m -Xmx512m
    depends_on:
      - db
    volumes:
      - sonarqube_data:/opt/sonarqube/data  # Volumen persistente para los datos de SonarQube
      - sonarqube_logs:/opt/sonarqube/logs  # Volumen persistente para los logs de SonarQube
      - sonarqube_extensions:/opt/sonarqube/extensions  # Volumen persistente para las extensiones
      - sonarqube_conf:/opt/sonarqube/conf  # Volumen persistente para las configuraciones

    networks:
      - sonarnet
      - my-network  # Añadir la red externa

  db:
    image: postgres:12
    container_name: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    networks:
      - sonarnet
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volumen persistente para la base de datos de PostgreSQL

networks:
  sonarnet:
    driver: bridge
  my-network:  # Declaración de la red externa
    external: true

volumes:
  sonarqube_data:  # Volumen persistente para SonarQube
  sonarqube_logs:  # Volumen persistente para los logs de SonarQube
  sonarqube_extensions:  # Volumen persistente para las extensiones de SonarQube
  sonarqube_conf:  # Volumen persistente para las configuraciones de SonarQube
  postgres_data:  # Volumen persistente para la base de datos de PostgreSQL
